### ISSUE TITLE
Why does the analytics object need to be FSA compliant?

### ISSUE THREAD

**Issue by ferdinandsalis** [markdalgleish/redux-analytics#1]
I tried using segment (https://segment.com/docs/libraries/analytics.js/) with redux-analytics and its api is bit more elaborate I guess. Wanted to do the following but its not possible since the analytics object needs be FSA compliant.

``` js
export default analytics(({method, subject, payload }) => {
  return segment[method](subject, payload);
});
```

**Comment by markdalgleish** [comment]
I decided to enforce FSA compliance on the analytics meta object so that plugins could more easily be created, since we can know 100% in advance the general shape of the object. I might revert this decision later, but I figured it's easier to start strict and work backwards from there.

In your case, I'd probably format the object like this:

``` js
meta: {
  analytics: {
    type: '...',
    payload: { ... },
    meta: { method: '...' }
  }
}
```

**Comment by ferdinandsalis** [comment]
@markdalgleish thanks
